services:
    php:
        container_name: wb_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        restart: unless-stopped

    mysql:
        container_name: wb_mysql
        image: mysql:8.0
        command: --port=3307
        ports:
            - "3307:3307"
        environment:
            MYSQL_DATABASE: wb_import
            MYSQL_USER: wb_import
            MYSQL_PASSWORD: wb_import
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    mysql_data:
